[ids]
*

[main]
# hyper key
capslock = overload(hyper, esc)

# mac-like editing shortcuts
leftalt = layer(command)

[hyper]

# arrows
h = left
j = down
k = up
l = right

# sesh launcher
space = menu

# tmux workflow
#v = macro(C-a |)
#b = macro(C-a -)
#z = macro(C-a z)
#x = macro(C-a x)
#n = macro(C-a n)
#p = macro(C-a p)
#c = macro(C-a c)
v = S-C-A-M-v
b = S-C-A-M-b
x = S-C-A-M-x
z = S-C-A-M-z
n = S-C-A-M-n
p = S-C-A-M-p
c = S-C-A-M-c

[command]

# mac-like clipboard shortcuts
c = C-c
v = C-v
x = C-x
