# shellcheck shell=bash

alias refresh='source ~/.bash_profile'
alias bsconf='vim ~/.config/bash; refresh'
alias tmconf='vim ~/.tmux.conf'
alias nvconf='vim ~/.config/nvim'
alias a='vim ~/.config/bash/aliases.sh; refresh'
alias c='clear'
alias e='exit'
alias h='history'
alias b='gh repo view d069147/bookmarks --web'
alias vb='cd ~/work/d069147/bookmarks && git pull; v README.md; git add README.md; git commit -m "update"; git push; cd -'
alias s='nvim ~/.secrets/'
alias ar='. assume-role.sh'
alias vs='vault-setup'

alias -- -='cd -'

alias ls='eza --group-directories-first'
alias ll='eza -l -snew'
alias l='eza -l --no-user --no-permissions -snew'
alias la='ls -a'
alias lsd='l -D'
alias lf='l -f'
alias llf='eza -l -f -snew'
alias llsd='eza -l -D -snew'

alias ct='column -t'
alias info='info --vi-keys'

alias adddirs='ls -d */ | xargs -I {} zoxide add {}'

alias a2restart='sudo service apache2 restart'
alias sss='python -m http.server 8888'

alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias g='git'
alias gg='git grep'
alias gs='git status'
alias gp='git pull'
alias gho='GH_HOST= gh repo view --web'
alias k='kubectl'
alias unrar='unrar x'
alias gtypist='gtypist -S'
alias ed='ed -p:'
alias wget='wget -c '
alias addup='paste -sd+ - | bc'
alias explain='GH_HOST=github.com gh copilot explain'
alias pbp='clipboard_paste'